export default {
  frame: {
      list_title: 'Notice List',
      list_tag_top: 'Top',
      list_tag_emergency: 'Emergency',
      list_tag_important: 'Important',
    sysInform: 'System Informs',
    loadingMore: 'Loading more ...',
    doc: 'Detail docs',
    warning: 'The server is busy, please try again later ...',
    top: 'Top',
    expiryDate: 'Expiry Date',
    to: 'to',
    relatedFiles: 'Related Files',
    home: 'Home',
    list: 'Notice List',
    title: 'Notice List',
    listDetail: 'Notice Detail',
    systemInfo: 'System Info',
    systemInfoContent: 'Your token is invalid, please try login again',
    pagerFooter: 'China Mobile International Limited. All rights reserved.',
    changeTitle: 'Change Password',
    accountId: 'Account Id',
    oldPsd: 'Old Password',
    newPsd: 'New Password',
    confirmNew: 'Confirm New',
    mobileNum: 'Mobile Number',
    psdRule: 'Password Rules',
    rule1: 'The length of new password must be more than seven',
    rule2: 'Password can include three of the follow three types:',
    rule3: 'Upper case letters from A to Z',
    rule4: 'case letters from a to z',
    rule5: 'numbers from 0 to 9',
    rule6: 'password is effectively in 90 days',
    submit: 'Submit',
    check: 'New password is not consistent with the confirmed password',
    inputNull: 'Input cannot be empty',
    btn_yes: 'OK',
    change_psd: 'Change Password'
  },
  notice_local:{
    notice: {
      one_select:'You can only manipulate one piece of data',
      create_success:'New Bulletin Success',
      create_erromessge:'New Bulletin Fail',
      update_success:'Update Bulletin Success',
      update_erromessge:'Update Bulletin Fail',
      logout_success:'Successful Logout',
      logout_fail:'The Logout Is Not Successful',
      verify_time:'The Effective Time Must Be Less Than The Failure Time',
      logout_erromessge:'The Logout Operation Cannot Be Performed',
      update_erromessge:'Unable To Modify Operation',
      qry_erromessge:'Query Operation Failed',
      logout_erromessge_select:'Please Select Operation Information.',
      title: 'home',
      sub_title: 'System Management ',
      main_title: 'Notice Management',
      query_title: 'Title',
      query_state: 'State',
      query_effective: 'Effective Day',
      query_expiry: 'Expiry Day',
      query_btn: 'Query',
      query_new: 'New',
      tab_id: 'Notice ID',
      tab_title: 'Title',
        logout_btn: 'LogOut',
      tab_level: 'Notice Level',
      tab_range: 'Publish Range',
      tab_state: 'State',
      tab_effective: 'Effective Day',
      tab_expiry: 'Expiry Day',
      tab_creat: 'Creation Day',
      tab_operation: 'Operation',
      tab_modify: 'Modify',
      tab_detail: 'Detail',
      tab_delete: 'Delete',
      pop_role_search: 'Search',
      pop_role_title: '角色选择',
      pop_role_code: 'Role Code',
      pop_role_name: 'Role Name',
      pop_ok: 'OK',
      pop_notice: '公告信息',
      pop_notice_state: 'Display State',
      pop_notice_content: 'Content',
      pop_notice_stick: 'Stick Top',
      pop_notice_unit: 'Publish Unit',
      pop_notice_role: 'Publish Role',
      pop_submit: 'Submit',
      pop_modify_title: 'Modify Notice ',
      list_title: 'Notice List',
      list_tag_top: 'Top',
      list_tag_emergency: 'Emergency',
      list_tag_important: 'Important',
    },
  }
}
