export default {
  frame: {
    sysInform: '系统消息',
    loadingMore: '加载更多...',
    doc: '详细文档',
    warning: '服务器繁忙，请稍后再试 ...',
    top: '置顶',
    expiryDate: '有效周期',
    to: '至',
    relatedFiles: '相关附件',
    home: '首页',
    list: '消息列表',
    title: '消息列表',
    listDetail: '消息详情',
    systemInfo: '系统消息',
    systemInfoContent: '您的token已失效，请尝试重新登录！',
    pagerFooter: '中国移动国际有限公司 版权所有',
    changeTitle: '修改密码',
    accountId: '用户ID',
    oldPsd: '旧密码',
    newPsd: '新密码',
    confirmNew: '确认新密码',
    mobileNum: '手机号码',
    psdRule: '密码规则',
    rule1: '8位或以上长度',
    rule2: '包含来自以下三类:',
    rule3: '大写英文字母（从 A 到 Z）',
    rule4: '小写英文字母（从 a 到 z）',
    rule5: '10 个基本数字（从 0 到 9）',
    rule6: '密码有效时间为90天',
    submit: '提交',
    check: '新密码与确认密码不一致',
    inputNull: '输入框不能为空',
    btn_yes: '确定',
    change_psd: '修改密码'
  },
  notice_local: {
    notice: {
      create_success:'新增公告成功',
      create_erromessge:'新增公告失败',
      update_success:'修改公告成功',
      update_erromessge:'修改公告失败',
      logout_success:'注销操作成功',
      logout_fail:'注销操作不成功',
      verify_time:'生效时间必须小于失效时间',
      logout_erromessge:'无法进行注销操作',
      one_select:'只能操作一条数据',
      logout_erromessge_select:'请选择操作信息',
      update_erromessge:'无法进行修改操作',
      qry_erromessge:'查询操作失败',
      title: 'home',
      sub_title: '系统管理',
      main_title: '公告管理',
      query_title: '公告标题',
      query_state: '公告状态',
      query_effective: '生效时间',
      query_expiry: '失效时间',
      query_btn: '查询',
      query_new: '新增',
      logout_btn: '注销',
      tab_id: '公告ID',
      tab_title: '公告标题',
      tab_level: '公告级别',
      tab_range: '发布级别',
      tab_state: '显示状态',
      tab_effective: '生效时间',
      tab_expiry: '失效时间',
      tab_creat: '创建时间',
      tab_operation: '操作',
      tab_modify: '修改',
      tab_detail: '详情',
      tab_delete: '删除',
      pop_modify_title:'公告标题',
      pop_notice_state:'显示状态',
      pop_notice_content:'公告内容',
      pop_notice_stick:'是否置顶',
      pop_notice_unit:'发布单位',
      pop_notice_role:'发布角色',
      pop_submit:'提交',
      list_title: '公告列表',
      list_tag_top: '置顶',
      list_tag_emergency: '紧急',
      list_tag_important: '重要',
    },
  }
}
